### ISSUE TITLE
Farmer life: NaN/12

### ISSUE THREAD

**Issue by karv** [Klatu1494/carlos#3]
Después de golpearlo una vez con el arquero (con el guerrero sí calcula bien la vida) la Life del granjero se hace NaN

[bug]

**Comment by karv** [comment]
Probé con el resto de las unidades, sólo pasa con el arquero.

**Comment by Klatu1494** [comment]
Arreglado en este [commit](https://github.com/Klatu1494/carlos/commit/50c356114f9dda33383b62e8e0b8e941ff5f0fae).
